; Magento 2.4.9 PHP configuration
memory_limit = 756M
max_execution_time = 18000
max_input_time = 90
upload_max_filesize = 64M
post_max_size = 64M
max_input_vars = 75000
date.timezone = UTC
expose_php = Off
session.gc_maxlifetime = 8640

; Required for Magento
always_populate_raw_post_data = -1
suhosin.session.cryptua = Off
